// Mocks generated by Mockito 5.4.0 from annotations
// in pokedex_challenge/test/modules/home/home_controller_tests.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_challenge/data/modules/home/response/pokemon_redirect_resource_response.dart'
    as _i5;
import 'package:pokedex_challenge/data/modules/home/response/pokemon_response.dart'
    as _i2;
import 'package:pokedex_challenge/data/modules/home/service/pokemon_service_contract.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonResponse_0 extends _i1.SmartFake
    implements _i2.PokemonResponse {
  _FakePokemonResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonServiceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonServiceContract extends _i1.Mock
    implements _i3.PokemonServiceContract {
  @override
  _i4.Future<List<_i5.PokemonRedirectResourceResponse>>
      getBasicPaginatedPokemons({
    int? limit = 10,
    required int? offset,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getBasicPaginatedPokemons,
              [],
              {
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue:
                _i4.Future<List<_i5.PokemonRedirectResourceResponse>>.value(
                    <_i5.PokemonRedirectResourceResponse>[]),
            returnValueForMissingStub:
                _i4.Future<List<_i5.PokemonRedirectResourceResponse>>.value(
                    <_i5.PokemonRedirectResourceResponse>[]),
          ) as _i4.Future<List<_i5.PokemonRedirectResourceResponse>>);
  @override
  _i4.Future<_i2.PokemonResponse> getPokemonByUrl({required String? url}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonByUrl,
          [],
          {#url: url},
        ),
        returnValue:
            _i4.Future<_i2.PokemonResponse>.value(_FakePokemonResponse_0(
          this,
          Invocation.method(
            #getPokemonByUrl,
            [],
            {#url: url},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PokemonResponse>.value(_FakePokemonResponse_0(
          this,
          Invocation.method(
            #getPokemonByUrl,
            [],
            {#url: url},
          ),
        )),
      ) as _i4.Future<_i2.PokemonResponse>);
}
